### PR TITLE
Fix expandSelectedText breaking sentences for block changes

### LINKED ISSUE #1: Converting a line of text into a list item breaks the text after the first word
### Context
Converting a line of text into a list item

### Process
Place the cursor at the beginning of a line. Press the "Add a bulleted list" button in the toolbar.

### Current result
When converting a line of text into a list:
- adds the `- ` in front of the current line
- breaks the line after the first word

### Expected result
- adds the `- ` in front of the current line and doesn't introduce new lines

### Example
kapture 2018-08-22 at 13 18 24

### Possible Fix
I'm planning to look into this and raise a pull request, but I was wondering if there is a reason for having the current behaviour.

### PR DESCRIPTION
**Pull request by muan**
Fixes #1.

With section at the beginning of text–

### Unordered list

```
- Fix 

expandSelectedText breaking sentences for block changes
```

### Blockquote

```
> Fix 

expandSelectedText breaking sentences for block changes
```

### Unordered list

```
- Fix expandSelectedText breaking sentences for block changes
```

### Blockquote

```
> Fix expandSelectedText breaking sentences for block changes
```

## Ordered list

Ordered list has a special case behavior, which remains unchanged.

```
1.

Fix expandSelectedText breaking sentences for block changes
```

## Others

Inline markdown changes (bold/italic/link) remain on changed (ie will only expand to the first word). For example:

```
**Fix** expandSelectedText breaking sentences for block changes
```

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -256,9 +256,10 @@ function wordSelectionStart(text: string, i: number): number {
   return index
 }
 
-function wordSelectionEnd(text: string, i: number): number {
+function wordSelectionEnd(text: string, i: number, multiline: boolean): number {
   let index = i
-  while (text[index] && !text[index].match(/\s/)) {
+  const breakPoint = multiline ? /\n/ : /\s/
+  while (text[index] && !text[index].match(breakPoint)) {
```
Comment (muan) [inline index.js]: This is the fix. Previously when `selectionStart === selectionEnd`, text selection is expanded to the first occurrence of `space`. This changes it so selection is expanded to the first line break when appropriate (`ul`/`blockquote`/`task-lists`).
